name: Build

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  typecheck:
    name: Run typechecking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - name: Install node dependencies
        run: bun install -d
      - name: Run tests
        run: bun run typecheck

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - name: Install node dependencies
        run: bun install -d
      - name: Run tests
        run: bun run test

  integration-test:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - name: Install node dependencies
        run: bun install -d
      - uses: taiki-e/cache-cargo-install-action@v3
        name: Install cargo-workspaces
        with:
          tool: cargo-workspaces
      - name: Run tests
        run: bun run test:integration

  build: # make sure build/ci work properly
    name: Build Actions executable
    needs: [test, integration-test, typecheck]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - name: Install node dependencies
        run: |
          bun install
      - name: Build dist
        run: bun run build
      - name: Upload dist
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist

  action-test: # make sure the action works on a clean machine without building
    name: Test Actions
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/cache-cargo-install-action@v3
        name: Install cargo-workspaces
        with:
          tool: cargo-workspaces
      - name: Download dist
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist
      - name: Run tests
        uses: ./
        with:
          path: __tests__/fixtures/single-crate
          dry-run: true
          check-repo: ${{ github.event_name == 'push' }}
